version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass.123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql